export const sendPayment = () => {
  const url = `${process.env.BASE_URL}/transaction/payment`;
  const authorizationBearer =
    "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im5FSzVPTWNPV0pxTkRZZ3RienRXTyJ9.eyJpc3MiOiJodHRwczovL2Rldi1pdndldGJzYXNvemtqeGM3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJvVU9yRlZZV3pYRndiVjhtV2ZaZ2M2NjhHamt6bkhNa0BjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaWF0IjoxNjgzMjE0NjQ4LCJleHAiOjE2ODMzMDEwNDgsImF6cCI6Im9VT3JGVllXelhGd2JWOG1XZlpnYzY2OEdqa3puSE1rIiwic2NvcGUiOiJhZG1pbiIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbImFkbWluIl19.czdO0jV4GQUFj3TITjrUt3SMCe3sukkuS4Zr4sVpRXS0pXtyQkgYO-OUiWfLEmnpb6vGxS-TUhldhc2z9_DBp9ELefEwR9jsIkhSltsMZfmuvwTOaZR01y0aXagTuOzcX9c3fJjzMidUcfEdgCJqVKhsyEj_s-qDflZsCHPzfczDOuGa96JMqemVMdciglsc-fMRaYvGWiiqpfXrINY9yXxL723VV5zer4l4cZVftKWvs_DDrhbgqyCDZA04Dh-Go6bSkMqAtKdneJSzCNnDR9_IoslXdvRpQsKQSbj1mW_BfpVrQC6r3T2BlEB2-uCoPnU_Ho2x1wFki8coGDOjbg";
};
